/* Add spell 5437 (Corruptor's Boon) to WCIDs 29542 (Enscorcelled Robe) that don't already have that spell */

INSERT INTO BIOTA_PROPERTIES_SPELL_BOOK
(SELECT DISTINCT b1.ID, 5437, 2 FROM BIOTA b1
WHERE b1.WEENIE_CLASS_ID = 29542 
AND b1.ID NOT IN (SELECT DISTINCT b2.ID FROM BIOTA b2
INNER JOIN BIOTA_PROPERTIES_SPELL_BOOK bpsb on bpsb.OBJECT_ID = b2.ID
WHERE b2.WEENIE_CLASS_ID = 29542 AND bpsb.SPELL = 5437)
);
