using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ACE.Common;
using ACE.Entity.Enum;
using MySql.Data.MySqlClient;
using Newtonsoft.Json;

namespace ACE.Entity
{
    [DbTable("subscription", HasAutoGeneratedId = true, AutoGeneratedIdColumn = "subscriptionId")]
    public class Subscription
    {
        public Subscription()
        {
            SubscriptionGuid = Guid.NewGuid();
        }

        [DbField("subscriptionId", (int)MySqlDbType.UInt32, Insert = false, IsCriteria = true, Update = false)]
        [JsonProperty("subscriptionId")]
        public uint SubscriptionId { get; set; }

        [JsonProperty("subscriptionGuid")]
        public Guid SubscriptionGuid { get; set; }

        [DbField("subscriptionGuid", (int)MySqlDbType.Binary, Update = false)]
        [JsonIgnore]
        public byte[] SubscriptionGuid_Binder
        {
            get { return SubscriptionGuid.ToByteArray(); }
            set { SubscriptionGuid = new Guid(value); }
        }

        [JsonProperty("accountGuid")]
        public Guid AccountGuid { get; set; }

        [DbField("accountGuid", (int)MySqlDbType.Binary, Update = false, ListGet = true)]
        [JsonIgnore]
        public byte[] AccountGuid_Binder
        {
            get { return AccountGuid.ToByteArray(); }
            set { AccountGuid = new Guid(value); }
        }

        [JsonIgnore]
        public AccessLevel AccessLevel { get; set; }

        [DbField("accessLevel", (int)MySqlDbType.UInt32)]
        [JsonProperty("accessLevel")]
        public uint AccessLevel_Binder
        {
            get { return (uint)AccessLevel; }
            set { AccessLevel = (AccessLevel)value; }
        }

        [DbField("subscriptionName", (int)MySqlDbType.Text)]
        [JsonProperty("name")]
        public string Name { get; set; }
    }
}
