USE `ace_world`;

CREATE TABLE `spell` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Id of this Spell',
  `spell_Id` int(10) unsigned NOT NULL COMMENT 'Unique Spell Id',
  `name` text NOT NULL,
  `description` text NOT NULL,
  `school` int(10) NOT NULL DEFAULT '0',
  `icon_Id` int(10) unsigned NOT NULL DEFAULT '0',
  `category` int(10) unsigned NOT NULL DEFAULT '0',
  `bitfield` int(10) unsigned NOT NULL DEFAULT '0',
  `mana` int(10) unsigned NOT NULL DEFAULT '0',
  `range_Constant` float NOT NULL,
  `range_Mod` float NOT NULL,
  `power` int(10) unsigned NOT NULL DEFAULT '0',
  `economy_Mod` float NOT NULL,
  `formula_Version` int(10) unsigned NOT NULL DEFAULT '0',
  `component_Loss` float NOT NULL,
  `meta_Spell_Type` int(10) NOT NULL DEFAULT '0',
  `meta_Spell_Id` int(10) unsigned NOT NULL DEFAULT '0',
  `spell_Formula_Comp_1_Component_Id` int(10) unsigned NOT NULL DEFAULT '0',
  `spell_Formula_Comp_2_Component_Id` int(10) unsigned NOT NULL DEFAULT '0',
  `spell_Formula_Comp_3_Component_Id` int(10) unsigned NOT NULL DEFAULT '0',
  `spell_Formula_Comp_4_Component_Id` int(10) unsigned NOT NULL DEFAULT '0',
  `spell_Formula_Comp_5_Component_Id` int(10) unsigned NOT NULL DEFAULT '0',
  `spell_Formula_Comp_6_Component_Id` int(10) unsigned NOT NULL DEFAULT '0',
  `spell_Formula_Comp_7_Component_Id` int(10) unsigned NOT NULL DEFAULT '0',
  `spell_Formula_Comp_8_Component_Id` int(10) unsigned NOT NULL DEFAULT '0',
  `caster_Effect` int(10) unsigned NOT NULL DEFAULT '0',
  `target_Effect` int(10) unsigned NOT NULL DEFAULT '0',
  `fizzle_Effect` int(10) unsigned NOT NULL DEFAULT '0',
  `recovery_Interval` double NOT NULL,
  `recovery_Amount` float NOT NULL,
  `display_Order` int(10) unsigned NOT NULL DEFAULT '0',
  `non_Component_Target_Type` int(10) unsigned NOT NULL DEFAULT '0',
  `mana_Mod` int(10) unsigned NOT NULL DEFAULT '0',
  `duration` double DEFAULT NULL,
  `degrade_Modifier` float DEFAULT NULL,
  `degrade_Limit` float DEFAULT NULL,
  `stat_Mod_Type` int(10) unsigned DEFAULT NULL,
  `stat_Mod_Key` int(10) unsigned DEFAULT NULL,
  `stat_Mod_Val` float DEFAULT NULL,
  `e_Type` int(10) unsigned DEFAULT NULL,
  `base_Intensity` int(10) DEFAULT NULL,
  `variance` int(10) DEFAULT NULL,
  `wcid` int(10) unsigned DEFAULT NULL,
  `num_Projectiles` int(10) DEFAULT NULL,
  `num_Projectiles_Variance` int(10) DEFAULT NULL,
  `spread_Angle` float DEFAULT NULL,
  `vertical_Angle` float DEFAULT NULL,
  `default_Launch_Angle` float DEFAULT NULL,
  `non_Tracking` bit(1) DEFAULT NULL,
  `create_Offset_Origin_X` float DEFAULT NULL,
  `create_Offset_Origin_Y` float DEFAULT NULL,
  `create_Offset_Origin_Z` float DEFAULT NULL,
  `padding_Origin_X` float DEFAULT NULL,
  `padding_Origin_Y` float DEFAULT NULL,
  `padding_Origin_Z` float DEFAULT NULL,
  `dims_Origin_X` float DEFAULT NULL,
  `dims_Origin_Y` float DEFAULT NULL,
  `dims_Origin_Z` float DEFAULT NULL,
  `peturbation_Origin_X` float DEFAULT NULL,
  `peturbation_Origin_Y` float DEFAULT NULL,
  `peturbation_Origin_Z` float DEFAULT NULL,
  `imbued_Effect` int(10) unsigned DEFAULT NULL,
  `slayer_Creature_Type` int(10) DEFAULT NULL,
  `slayer_Damage_Bonus` float DEFAULT NULL,
  `crit_Freq` double DEFAULT NULL,
  `crit_Multiplier` double DEFAULT NULL,
  `ignore_Magic_Resist` int(10) DEFAULT NULL,
  `elemental_Modifier` double DEFAULT NULL,
  `drain_Percentage` float DEFAULT NULL,
  `damage_Ratio` float DEFAULT NULL,
  `damage_Type` int(10) DEFAULT NULL,
  `boost` int(10) DEFAULT NULL,
  `boost_Variance` int(10) DEFAULT NULL,
  `source` int(10) DEFAULT NULL,
  `destination` int(10) DEFAULT NULL,
  `proportion` float DEFAULT NULL,
  `loss_Percent` float DEFAULT NULL,
  `source_Loss` int(10) DEFAULT NULL,
  `transfer_Cap` int(10) DEFAULT NULL,
  `max_Boost_Allowed` int(10) DEFAULT NULL,
  `transfer_Bitfield` int(10) unsigned DEFAULT NULL,
  `index` int(10) DEFAULT NULL,
  `portal_Lifetime` double DEFAULT NULL,
  `link` int(10) DEFAULT NULL,
  `position_Obj_Cell_ID` int(10) unsigned DEFAULT NULL,
  `position_Origin_X` float DEFAULT NULL,
  `position_Origin_Y` float DEFAULT NULL,
  `position_Origin_Z` float DEFAULT NULL,
  `position_Angles_W` float DEFAULT NULL,
  `position_Angles_X` float DEFAULT NULL,
  `position_Angles_Y` float DEFAULT NULL,
  `position_Angles_Z` float DEFAULT NULL,
  `min_Power` int(10) DEFAULT NULL,
  `max_Power` int(10) DEFAULT NULL,
  `power_Variance` float DEFAULT NULL,
  `dispel_School` int(10) DEFAULT NULL,
  `align` int(10) DEFAULT NULL,
  `number` int(10) DEFAULT NULL,
  `number_Variance` float DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `spell_id_uidx` (`spell_Id`),
  UNIQUE KEY `metaspell_id_uidx` (`meta_Spell_Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Spell Table Extended Data';
