CREATE TABLE IF NOT EXISTS `treasure_death` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Id of this Treasure',
  `treasure_Type` int(10) unsigned NOT NULL COMMENT 'Type of Treasure for this instance',
  `tier` int(10) NOT NULL,
  `unknown_1` float NOT NULL,
  `unknown_2` int(10) NOT NULL,
  `unknown_3` int(10) NOT NULL,
  `unknown_4` int(10) NOT NULL,
  `unknown_5` int(10) NOT NULL,
  `unknown_6` int(10) NOT NULL,
  `unknown_7` int(10) NOT NULL,
  `unknown_8` int(10) NOT NULL,
  `unknown_9` int(10) NOT NULL,
  `unknown_10` int(10) NOT NULL,
  `unknown_11` int(10) NOT NULL,
  `unknown_12` int(10) NOT NULL,
  `unknown_13` int(10) NOT NULL,
  `unknown_14` int(10) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `treasureType_idx` (`treasure_Type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Death Treasure';
