USE `ace_world`;

ALTER TABLE `spell` 
DROP COLUMN `portal_Lifetime`,
DROP COLUMN `degrade_Limit`,
DROP COLUMN `degrade_Modifier`,
DROP COLUMN `duration`,
DROP COLUMN `mana_Mod`,
DROP COLUMN `non_Component_Target_Type`,
DROP COLUMN `display_Order`,
DROP COLUMN `recovery_Amount`,
DROP COLUMN `recovery_Interval`,
DROP COLUMN `fizzle_Effect`,
DROP COLUMN `target_Effect`,
DROP COLUMN `caster_Effect`,
DROP COLUMN `spell_Formula_Comp_8_Component_Id`,
DROP COLUMN `spell_Formula_Comp_7_Component_Id`,
DROP COLUMN `spell_Formula_Comp_6_Component_Id`,
DROP COLUMN `spell_Formula_Comp_5_Component_Id`,
DROP COLUMN `spell_Formula_Comp_4_Component_Id`,
DROP COLUMN `spell_Formula_Comp_3_Component_Id`,
DROP COLUMN `spell_Formula_Comp_2_Component_Id`,
DROP COLUMN `spell_Formula_Comp_1_Component_Id`,
DROP COLUMN `meta_Spell_Id`,
DROP COLUMN `meta_Spell_Type`,
DROP COLUMN `component_Loss`,
DROP COLUMN `formula_Version`,
DROP COLUMN `economy_Mod`,
DROP COLUMN `power`,
DROP COLUMN `range_Mod`,
DROP COLUMN `range_Constant`,
DROP COLUMN `mana`,
DROP COLUMN `bitfield`,
DROP COLUMN `category`,
DROP COLUMN `icon_Id`,
DROP COLUMN `school`,
DROP COLUMN `description`,
DROP INDEX `metaspell_id_uidx` ;
;
