# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for NuGet
  - package-ecosystem: "nuget"
    directory: "/Source"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 15
    ignore:
      # Ignore major version updates for the following
      - dependency-name: "System.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.EntityFrameworkCore"
        update-types: ["version-update:semver-major"]
      - dependency-name: "log4net"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "dotnet/sdk"
        # For dotnet/runtime, ignore all updates for version 7
        versions: ["7.x"]
      - dependency-name: "dotnet/runtime"
        # For dotnet/runtime, ignore all updates for version 7
        versions: ["7.x"]
