using System;

namespace ACE.Server.WorldObjects
{
    partial class WorldObject
    {
        /// <summary>
        /// The default number of seconds for a object on a landblock to disappear<para />
        /// Current default is 5 minutes
        /// </summary>
        protected virtual TimeSpan DefaultTimeToRot { get; set; } = TimeSpan.FromMinutes(5);

        /// <summary>
        /// A decayable object is one that, when it exists on a landblock, would decay (rot) over time.<para />
        /// When it rots, it would be destroyed, and removed from the landblock.<para />
        /// In most cases, these should be player dropped items or corpses. It can also be a missile or spell projectile.<para />
        /// Generators and items still linked to a generator will return false.
        /// </summary>
        public bool IsDecayable()
        {
            if (!Guid.IsDynamic())
                return false;

            // Don't rot generators, and items that were generated by a generator
            // If the item was generated by a generator and then picked up by a player, the wo.Generator property would be set to null.
            if (IsGenerator || Generator != null)
                return false;

            return true;
        }

        private bool decayCompleted;

        public virtual void Decay(TimeSpan elapsed)
        {
            if (decayCompleted)
                return;

            if (!TimeToRot.HasValue)
            {
                TimeToRot = DefaultTimeToRot.TotalSeconds;
                return;
            }

            TimeToRot -= elapsed.TotalSeconds;

            // Is there still time left?
            if (TimeToRot > 0)
                return;

            // Time to rot has elapsed, time to disappear...
            decayCompleted = true;

            // TODO: if items are left on corpse,
            // create these items in the world
            // http://asheron.wikia.com/wiki/Item_Decay

            Destroy();
        }
    }
}
