version: '3'
services:

  db:
    image: mysql:latest
    container_name: ace-db
    env_file:
      - docker.env
    volumes:
      - C:\ACE\db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  ace:
    build: .
    image: acemulator/ace:latest
    depends_on:
      - db
    container_name: ace-server
    env_file:
      - docker.env
    volumes:
      - C:\ACE\Config:/ace/Config
      - C:\ACE\Content:/ace/Content
      - C:\ACE\Dats:/ace/Dats
      - C:\ACE\Logs:/ace/Logs
    ports:
      - "9000-9001:9000-9001/udp"
    #restart: unless-stopped
    restart: on-failure

