using System.ComponentModel;

namespace ACE.Entity.Enum.Properties
{
    public enum PropertyInt : ushort
    {
        // properties marked as ServerOnly are properties we never saw in PCAPs, from here:
        // http://ac.yotesfan.com/ace_object/not_used_enums.php
        // source: @OptimShi
        // description attributes are used by the weenie editor for a cleaner display name

        Undef                                    = 0,
        [ServerOnly]
        ItemType                                 = 1,
        CreatureType                             = 2,
        [ServerOnly]
        PaletteTemplate                          = 3,
        ClothingPriority                         = 4,
        [Ephemeral]
        EncumbranceVal                           = 5, // ENCUMB_VAL_INT,
        [SendOnLogin]
        ItemsCapacity                            = 6,
        [SendOnLogin]
        ContainersCapacity                       = 7,
        [ServerOnly]
        Mass                                     = 8,
        [ServerOnly]
        ValidLocations                           = 9, // LOCATIONS_INT
        [ServerOnly]
        CurrentWieldedLocation                   = 10,
        [ServerOnly]
        MaxStackSize                             = 11,
        [ServerOnly]
        StackSize                                = 12,
        [ServerOnly]
        StackUnitEncumbrance                     = 13,
        [ServerOnly]
        StackUnitMass                            = 14,
        [ServerOnly]
        StackUnitValue                           = 15,
        [ServerOnly]
        ItemUseable                              = 16,
        RareId                                   = 17,
        [ServerOnly]
        UiEffects                                = 18,
        [Ephemeral]
        Value                                    = 19,
        [Ephemeral][ServerOnly][SendOnLogin]
        CoinValue                                = 20,
        TotalExperience                          = 21,
        AvailableCharacter                       = 22,
        TotalSkillCredits                        = 23,
        AvailableSkillCredits                    = 24,
        Level                                    = 25,
        AccountRequirements                      = 26,
        ArmorType                                = 27,
        ArmorLevel                               = 28,
        AllegianceCpPool                         = 29,
        AllegianceRank                           = 30,
        ChannelsAllowed                          = 31,
        ChannelsActive                           = 32,
        Bonded                                   = 33,
        MonarchsRank                             = 34,
        AllegianceFollowers                      = 35,
        ResistMagic                              = 36,
        ResistItemAppraisal                      = 37,
        ResistLockpick                           = 38,
        DeprecatedResistRepair                   = 39,
        CombatMode                               = 40,
        CurrentAttackHeight                      = 41,
        CombatCollisions                         = 42,
        NumDeaths                                = 43,
        Damage                                   = 44,
        DamageType                               = 45,
        [ServerOnly]
        DefaultCombatStyle                       = 46,
        AttackType                               = 47,
        WeaponSkill                              = 48,
        WeaponTime                               = 49,
        AmmoType                                 = 50,
        CombatUse                                = 51,
        [ServerOnly]
        ParentLocation                           = 52,
        [ServerOnly]
        PlacementPosition                        = 53,
        WeaponEncumbrance                        = 54,
        WeaponMass                               = 55,
        ShieldValue                              = 56,
        ShieldEncumbrance                        = 57,
        MissileInventoryLocation                 = 58,
        FullDamageType                           = 59,
        WeaponRange                              = 60,
        AttackersSkill                           = 61,
        DefendersSkill                           = 62,
        AttackersSkillValue                      = 63,
        AttackersClass                           = 64,
        [ServerOnly]
        Placement                                = 65,
        CheckpointStatus                         = 66,
        Tolerance                                = 67,
        TargetingTactic                          = 68,
        CombatTactic                             = 69,
        HomesickTargetingTactic                  = 70,
        NumFollowFailures                        = 71,
        FriendType                               = 72,
        FoeType                                  = 73,
        MerchandiseItemTypes                     = 74,
        MerchandiseMinValue                      = 75,
        MerchandiseMaxValue                      = 76,
        NumItemsSold                             = 77,
        NumItemsBought                           = 78,
        MoneyIncome                              = 79,
        MoneyOutflow                             = 80,
        MaxGeneratedObjects                      = 81,
        InitGeneratedObjects                     = 82,
        ActivationResponse                       = 83,
        OriginalValue                            = 84,
        NumMoveFailures                          = 85,
        MinLevel                                 = 86,
        MaxLevel                                 = 87,
        LockpickMod                              = 88,
        [ServerOnly]
        BoosterEnum                              = 89,
        BoostValue                               = 90,
        MaxStructure                             = 91,
        Structure                                = 92,
        [ServerOnly]
        PhysicsState                             = 93,
        [ServerOnly]
        TargetType                               = 94,
        [Ephemeral]
        RadarBlipColor                           = 95,
        EncumbranceCapacity                      = 96,
        LoginTimestamp                           = 97,
        CreationTimestamp                        = 98,
        PkLevelModifier                          = 99,
        GeneratorType                            = 100,
        AiAllowedCombatStyle                     = 101,
        LogoffTimestamp                          = 102,
        GeneratorDestructionType                 = 103,
        ActivationCreateClass                    = 104,
        ItemWorkmanship                          = 105,
        ItemSpellcraft                           = 106,
        ItemCurMana                              = 107,
        ItemMaxMana                              = 108,
        ItemDifficulty                           = 109,
        ItemAllegianceRankLimit                  = 110,
        PortalBitmask                            = 111,
        AdvocateLevel                            = 112,
        Gender                                   = 113,
        Attuned                                  = 114,
        ItemSkillLevelLimit                      = 115,
        GateLogic                                = 116,
        ItemManaCost                             = 117,
        Logoff                                   = 118,
        Active                                   = 119,
        AttackHeight                             = 120,
        NumAttackFailures                        = 121,
        AiCpThreshold                            = 122,
        AiAdvancementStrategy                    = 123,
        Version                                  = 124,
        Age                                      = 125,
        VendorHappyMean                          = 126,
        VendorHappyVariance                      = 127,
        CloakStatus                              = 128,
        VitaeCpPool                              = 129,
        NumServicesSold                          = 130,
        MaterialType                             = 131,
        NumAllegianceBreaks                      = 132,
        [Ephemeral]
        ShowableOnRadar                          = 133,
        PlayerKillerStatus                       = 134,
        VendorHappyMaxItems                      = 135,
        ScorePageNum                             = 136,
        ScoreConfigNum                           = 137,
        ScoreNumScores                           = 138,
        DeathLevel                               = 139,
        AiOptions                                = 140,
        OpenToEveryone                           = 141,
        GeneratorTimeType                        = 142,
        GeneratorStartTime                       = 143,
        GeneratorEndTime                         = 144,
        GeneratorEndDestructionType              = 145,
        XpOverride                               = 146,
        NumCrashAndTurns                         = 147,
        ComponentWarningThreshold                = 148,
        HouseStatus                              = 149,
        [ServerOnly]
        HookPlacement                            = 150,
        [ServerOnly]
        HookType                                 = 151,
        [ServerOnly]
        HookItemType                             = 152,
        AiPpThreshold                            = 153,
        GeneratorVersion                         = 154,
        HouseType                                = 155,
        PickupEmoteOffset                        = 156,
        WeenieIteration                          = 157,
        WieldRequirements                        = 158,
        WieldSkilltype                           = 159,
        WieldDifficulty                          = 160,
        HouseMaxHooksUsable                      = 161,
        HouseCurrentHooksUsable                  = 162,
        AllegianceMinLevel                       = 163,
        AllegianceMaxLevel                       = 164,
        HouseRelinkHookCount                     = 165,
        SlayerCreatureType                       = 166,
        ConfirmationInProgress                   = 167,
        ConfirmationTypeInProgress               = 168,
        TsysMutationData                         = 169,
        NumItemsInMaterial                       = 170,
        NumTimesTinkered                         = 171,
        AppraisalLongDescDecoration              = 172,
        AppraisalLockpickSuccessPercent          = 173,
        [Ephemeral]
        AppraisalPages                           = 174,
        [Ephemeral]
        AppraisalMaxPages                        = 175,
        AppraisalItemSkill                       = 176,
        GemCount                                 = 177,
        GemType                                  = 178,
        ImbuedEffect                             = 179,
        AttackersRawSkillValue                   = 180,
        ChessRank                                = 181,
        ChessTotalGames                          = 182,
        ChessGamesWon                            = 183,
        ChessGamesLost                           = 184,
        TypeOfAlteration                         = 185,
        SkillToBeAltered                         = 186,
        SkillAlterationCount                     = 187,
        HeritageGroup                            = 188,
        TransferFromAttribute                    = 189,
        TransferToAttribute                      = 190,
        AttributeTransferCount                   = 191,
        FakeFishingSkill                         = 192,
        NumKeys                                  = 193,
        DeathTimestamp                           = 194,
        PkTimestamp                              = 195,
        VictimTimestamp                          = 196,
        HookGroup                                = 197,
        AllegianceSwearTimestamp                 = 198,
        HousePurchaseTimestamp                   = 199,
        RedirectableEquippedArmorCount           = 200,
        MeleedefenseImbuedEffectTypeCache        = 201,
        MissileDefenseImbuedEffectTypeCache      = 202,
        MagicDefenseImbuedEffectTypeCache        = 203,
        ElementalDamageBonus                     = 204,
        ImbueAttempts                            = 205,
        ImbueSuccesses                           = 206,
        CreatureKills                            = 207,
        PlayerKillsPk                            = 208,
        PlayerKillsPkl                           = 209,
        RaresTierOne                             = 210,
        RaresTierTwo                             = 211,
        RaresTierThree                           = 212,
        RaresTierFour                            = 213,
        RaresTierFive                            = 214,
        AugmentationStat                         = 215,
        AugmentationFamilyStat                   = 216,
        AugmentationInnateFamily                 = 217,
        AugmentationInnateStrength               = 218,
        AugmentationInnateEndurance              = 219,
        AugmentationInnateCoordination           = 220,
        AugmentationInnateQuickness              = 221,
        AugmentationInnateFocus                  = 222,
        AugmentationInnateSelf                   = 223,
        AugmentationSpecializeSalvaging          = 224,
        AugmentationSpecializeItemTinkering      = 225,
        AugmentationSpecializeArmorTinkering     = 226,
        AugmentationSpecializeMagicItemTinkering = 227,
        AugmentationSpecializeWeaponTinkering    = 228,
        AugmentationExtraPackSlot                = 229,
        AugmentationIncreasedCarryingCapacity    = 230,
        AugmentationLessDeathItemLoss            = 231,
        AugmentationSpellsRemainPastDeath        = 232,
        AugmentationCriticalDefense              = 233,
        AugmentationBonusXp                      = 234,
        AugmentationBonusSalvage                 = 235,
        AugmentationBonusImbueChance             = 236,
        AugmentationFasterRegen                  = 237,
        AugmentationIncreasedSpellDuration       = 238,
        AugmentationResistanceFamily             = 239,
        AugmentationResistanceSlash              = 240,
        AugmentationResistancePierce             = 241,
        AugmentationResistanceBlunt              = 242,
        AugmentationResistanceAcid               = 243,
        AugmentationResistanceFire               = 244,
        AugmentationResistanceFrost              = 245,
        AugmentationResistanceLightning          = 246,
        RaresTierOneLogin                        = 247,
        RaresTierTwoLogin                        = 248,
        RaresTierThreeLogin                      = 249,
        RaresTierFourLogin                       = 250,
        RaresTierFiveLogin                       = 251,
        RaresLoginTimestamp                      = 252,
        RaresTierSix                             = 253,
        RaresTierSeven                           = 254,
        RaresTierSixLogin                        = 255,
        RaresTierSevenLogin                      = 256,
        ItemAttributeLimit                       = 257,
        ItemAttributeLevelLimit                  = 258,
        ItemAttribute2ndLimit                    = 259,
        ItemAttribute2ndLevelLimit               = 260,
        CharacterTitleId                         = 261,
        NumCharacterTitles                       = 262,
        ResistanceModifierType                   = 263,
        FreeTinkersBitfield                      = 264,
        EquipmentSetId                           = 265,
        PetClass                                 = 266,
        Lifespan                                 = 267,
        RemainingLifespan                        = 268,
        UseCreateQuantity                        = 269,
        WieldRequirements2                       = 270,
        WieldSkilltype2                          = 271,
        WieldDifficulty2                         = 272,
        WieldRequirements3                       = 273,
        WieldSkilltype3                          = 274,
        WieldDifficulty3                         = 275,
        WieldRequirements4                       = 276,
        WieldSkilltype4                          = 277,
        WieldDifficulty4                         = 278,
        Unique                                   = 279,
        SharedCooldown                           = 280,
        Faction1Bits                             = 281,
        Faction2Bits                             = 282,
        Faction3Bits                             = 283,
        Hatred1Bits                              = 284,
        Hatred2Bits                              = 285,
        Hatred3Bits                              = 286,
        SocietyRankCelhan                        = 287,
        SocietyRankEldweb                        = 288,
        SocietyRankRadblo                        = 289,
        HearLocalSignals                         = 290,
        HearLocalSignalsRadius                   = 291,
        Cleaving                                 = 292,
        AugmentationSpecializeGearcraft          = 293,
        AugmentationInfusedCreatureMagic         = 294,
        AugmentationInfusedItemMagic             = 295,
        AugmentationInfusedLifeMagic             = 296,
        AugmentationInfusedWarMagic              = 297,
        AugmentationCriticalExpertise            = 298,
        AugmentationCriticalPower                = 299,
        AugmentationSkilledMelee                 = 300,
        AugmentationSkilledMissile               = 301,
        AugmentationSkilledMagic                 = 302,
        ImbuedEffect2                            = 303,
        ImbuedEffect3                            = 304,
        ImbuedEffect4                            = 305,
        ImbuedEffect5                            = 306,
        DamageRating                             = 307,
        DamageResistRating                       = 308,
        AugmentationDamageBonus                  = 309,
        AugmentationDamageReduction              = 310,
        ImbueStackingBits                        = 311,
        HealOverTime                             = 312,
        CritRating                               = 313,
        CritDamageRating                         = 314,
        CritResistRating                         = 315,
        CritDamageResistRating                   = 316,
        HealingResistRating                      = 317,
        DamageOverTime                           = 318,
        ItemMaxLevel                             = 319,
        ItemXpStyle                              = 320,
        EquipmentSetExtra                        = 321,
        AetheriaBitfield                         = 322,
        HealingBoostRating                       = 323,
        HeritageSpecificArmor                    = 324,
        AlternateRacialSkills                    = 325,
        /// <summary>
        /// why was this defaulted to 1?  leaving comment
        /// </summary>
        AugmentationJackOfAllTrades              = 326,
        AugmentationResistanceNether             = 327,
        AugmentationInfusedVoidMagic             = 328,
        WeaknessRating                           = 329,
        NetherOverTime                           = 330,
        NetherResistRating                       = 331,
        LuminanceAward                           = 332,
        LumAugDamageRating                       = 333,
        LumAugDamageReductionRating              = 334,
        LumAugCritDamageRating                   = 335,
        LumAugCritReductionRating                = 336,
        LumAugSurgeEffectRating                  = 337,
        LumAugSurgeChanceRating                  = 338,
        LumAugItemManaUsage                      = 339,
        LumAugItemManaGain                       = 340,
        LumAugVitality                           = 341,
        LumAugHealingRating                      = 342,
        LumAugSkilledCraft                       = 343,
        LumAugSkilledSpec                        = 344,
        LumAugNoDestroyCraft                     = 345,
        RestrictInteraction                      = 346,
        OlthoiLootTimestamp                      = 347,
        OlthoiLootStep                           = 348,
        UseCreatesContractId                     = 349,
        DotResistRating                          = 350,
        LifeResistRating                         = 351,
        CloakWeaveProc                           = 352,
        WeaponType                               = 353,
        MeleeMastery                             = 354,
        RangedMastery                            = 355,
        SneakAttackRating                        = 356,
        RecklessnessRating                       = 357,
        DeceptionRating                          = 358,
        CombatPetRange                           = 359,
        WeaponAuraDamage                         = 360,
        WeaponAuraSpeed                          = 361,
        SummoningMastery                         = 362,
        HeartbeatLifespan                        = 363,
        UseLevelRequirement                      = 364,
        LumAugAllSkills                          = 365,
        UseRequiresSkill                         = 366,
        UseRequiresSkillLevel                    = 367,
        UseRequiresSkillSpec                     = 368,
        UseRequiresLevel                         = 369,
        GearDamage                               = 370,
        GearDamageResist                         = 371,
        GearCrit                                 = 372,
        GearCritResist                           = 373,
        GearCritDamage                           = 374,
        GearCritDamageResist                     = 375,
        GearHealingBoost                         = 376,
        GearNetherResist                         = 377,
        GearLifeResist                           = 378,
        GearMaxHealth                            = 379,
        Unknown380                               = 380,
        PKDamageRating                           = 381,
        PKDamageResistRating                     = 382,
        GearPKDamageRating                       = 383,
        GearPKDamageResistRating                 = 384,
        Unknown385                               = 385,
        /// <summary>
        /// Overpower chance % for endgame creatures.
        /// </summary>
        Overpower                                = 386,
        OverpowerResist                          = 387,
        // Client does not display accurately
        GearOverpower                            = 388,
        // Client does not display accurately
        GearOverpowerResist                      = 389,
        // Number of times a character has enlightened
        Enlightenment                            = 390,

        [ServerOnly]
        TotalLogins                              = 9001,
        //[ServerOnly]
        //DeletionTimestamp                        = 9002,
        [ServerOnly]
        CharacterOptions1                        = 9003,
        [ServerOnly]
        CharacterOptions2                        = 9004,
        //[ServerOnly]
        //LootTier                                 = 9005,
        //[ServerOnly]
        //GeneratorProbability                     = 9006,
        //[ServerOnly]
        //WeenieType                               = 9007 // I don't think this property type is needed anymore. We don't store the weenie type in the property bags, we store it as a separate field in the base objects.
    }

    public static class PropertyIntExtensions
    {
        public static string GetDescription(this PropertyInt prop)
        {
            var description = prop.GetAttributeOfType<DescriptionAttribute>();
            return description?.Description ?? prop.ToString();
        }
    }
}
