namespace ACE.Entity.Enum.Properties
{
    public enum PropertiesIid : uint
    {
        Undef = 1,
        Owner = 2,
        Container = 3,
        Wielder = 4,
        Freezer = 5,
        Viewer = 6,
        Generator = 7,
        Scribe = 8,
        CurrentCombatTarget = 9,
        CurrentEnemy = 10,
        ProjectileLauncher = 11,
        CurrentAttacker = 12,
        CurrentDamager = 13,
        CurrentFollowTarget = 14,
        CurrentAppraisalTarget = 15,
        CurrentFellowshipAppraisalTarget = 16,
        ActivationTarget = 17,
        Creator = 18,
        Victim = 19,
        Killer = 20,
        Vendor = 21,
        Customer = 22,
        Bonded = 23,
        Wounder = 24,
        Allegiance = 25,
        Patron = 26,
        Monarch = 27,
        CombatTarget = 28,
        HealthQueryTarget = 29,
        LastUnlocker = 30,
        CrashAndTurnTarget = 31,
        AllowedActivator = 32,
        HouseOwner = 33,
        House = 34,
        Slumlord = 35,
        ManaQueryTarget = 36,
        CurrentGame = 37,
        RequestedAppraisalTarget = 38,
        AllowedWielder = 39,
        AssignedTarget = 40,
        LimboSource = 41,
        Snooper = 42,
        TeleportedCharacter = 43,
        Pet = 44,
        PetOwner = 45,
        PetDevice = 46,
        Count = 46
    }
}
