ALTER TABLE character_stats
ADD COLUMN strengthRanks TINYINT(2) UNSIGNED NOT NULL DEFAULT 0 AFTER strength;

ALTER TABLE character_stats
ADD COLUMN enduranceRanks TINYINT(2) UNSIGNED NOT NULL DEFAULT 0 AFTER endurance;

ALTER TABLE character_stats
ADD COLUMN coordinationRanks TINYINT(2) UNSIGNED NOT NULL DEFAULT 0 AFTER coordination;

ALTER TABLE character_stats
ADD COLUMN quicknessRanks TINYINT(2) UNSIGNED NOT NULL DEFAULT 0 AFTER quickness;

ALTER TABLE character_stats
ADD COLUMN focusRanks TINYINT(2) UNSIGNED NOT NULL DEFAULT 0 AFTER focus;

ALTER TABLE character_stats
ADD COLUMN selfRanks TINYINT(2) UNSIGNED NOT NULL DEFAULT 0 AFTER self;

ALTER TABLE character_stats
ADD COLUMN healthRanks TINYINT(2) UNSIGNED NOT NULL DEFAULT 0 AFTER selfRanks;

ALTER TABLE character_stats
ADD COLUMN staminaRanks TINYINT(2) UNSIGNED NOT NULL DEFAULT 0 AFTER healthRanks;

ALTER TABLE character_stats
ADD COLUMN manaRanks TINYINT(2) UNSIGNED NOT NULL DEFAULT 0 AFTER staminaRanks;

ALTER TABLE character_stats
ADD COLUMN healthCurrent TINYINT(2) UNSIGNED NOT NULL DEFAULT 0 AFTER healthRanks;

ALTER TABLE character_stats
ADD COLUMN staminaCurrent TINYINT(2) UNSIGNED NOT NULL DEFAULT 0 AFTER staminaRanks;

ALTER TABLE character_stats
ADD COLUMN manaCurrent TINYINT(2) UNSIGNED NOT NULL DEFAULT 0 AFTER manaRanks;
