USE `ace_auth`;

ALTER TABLE `account`
ADD COLUMN `email_Address` VARCHAR(320) NOT NULL DEFAULT 'N/A' AFTER `accessLevel`,
ADD COLUMN `create_I_P` VARCHAR(64) NOT NULL DEFAULT 'N/A' AFTER `email_Address`,
ADD COLUMN `create_Time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `create_I_P`,
ADD COLUMN `last_Login_I_P` VARCHAR(64) NOT NULL DEFAULT 'N/A' AFTER `create_Time`,
ADD COLUMN `last_Login_Time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `last_Login_I_P`,
ADD COLUMN `isBanned` BIT(1) NULL AFTER `last_Login_Time`,
ADD COLUMN `banned_Time` DATETIME NULL AFTER `isBanned`,
ADD COLUMN `banned_By_Account_I_D` INT(10) UNSIGNED NULL AFTER `banned_Time`,
ADD COLUMN `ban_Expire_Time` DATETIME NULL AFTER `banned_By_Account_I_D`;
