CREATE DATABASE `ace_auth` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE DATABASE `ace_character` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE DATABASE `ace_world` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;