CREATE DATABASE IF NOT EXISTS `ace_auth` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS `ace_shard` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS `ace_world` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
