using System;

namespace ACE.Common
{
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public class DbTableAttribute : Attribute
    {
        public string DbTableName { get; }

        public DbTableAttribute(string tableName)
        {
            DbTableName = tableName;
        }

        public bool HasAutoGeneratedId { get; set; } = false;

        public string AutoGeneratedIdColumn { get; set; }
    }
}
