namespace ACE.Server.Factories.Enum
{
    public enum TreasureItemType_Orig
    {
        // retail
        Undef,
        Pyreal,
        Gem,
        Jewelry,
        ArtObject,
        Weapon,
        Armor,
        Clothing,
        Scroll,
        Caster,
        ManaStone,
        Consumable,
        HealKit,
        Lockpick,
        SpellComponent,
        LeatherArmor,
        StuddedLeatherArmor,
        ChainMailArmor,
        CovenantArmor,
        PlateMailArmor,
        HeritageLowArmor,
        HeritageHighArmor,
        SwordWeapon,
        MaceWeapon,
        AxeWeapon,
        SpearWeapon,
        UnarmedWeapon,
        StaffWeapon,
        DaggerWeapon,
        BowWeapon,
        CrossbowWeapon,
        AtlatlWeapon
    }
}
