DELETE FROM `weenie` WHERE `class_Id` = 450369;

INSERT INTO `weenie` (`class_Id`, `class_Name`, `type`, `last_Modified`)
VALUES (450369, 'shieldsanguinarygreentailor', 1, '2021-11-01 00:00:00') /* Generic */;

INSERT INTO `weenie_properties_int` (`object_Id`, `type`, `value`)
VALUES (450369,   1,          2) /* ItemType - Armor */
     , (450369,   3,          8) /* PaletteTemplate - Green */
     , (450369,   5,        0) /* EncumbranceVal */
     , (450369,   8,        140) /* Mass */
     , (450369,   9,    2097152) /* ValidLocations - Shield */
     , (450369,  16,          1) /* ItemUseable - No */
     , (450369,  19,          20) /* Value */
     , (450369,  27,          2) /* ArmorType - Leather */
     , (450369,  28,          0) /* ArmorLevel */
     , (450369,  51,          4) /* CombatUse - Shield */
     , (450369,  93,       1044) /* PhysicsState - Ethereal, IgnoreCollisions, Gravity */
     , (450369, 150,        103) /* HookPlacement - Hook */
     , (450369, 151,          2) /* HookType - Wall */;

INSERT INTO `weenie_properties_bool` (`object_Id`, `type`, `value`)
VALUES (450369,  22, True ) /* Inscribable */
     , (450369,  69, False) /* IsSellable */;

INSERT INTO `weenie_properties_float` (`object_Id`, `type`, `value`)
VALUES (450369,  13,       0) /* ArmorModVsSlash */
     , (450369,  14,       0) /* ArmorModVsPierce */
     , (450369,  15,       0) /* ArmorModVsBludgeon */
     , (450369,  16,       0) /* ArmorModVsCold */
     , (450369,  17,       0) /* ArmorModVsFire */
     , (450369,  18,       0) /* ArmorModVsAcid */
     , (450369,  19,       0) /* ArmorModVsElectric */
     , (450369,  39,       1) /* DefaultScale */
     , (450369, 110,       1) /* BulkMod */
     , (450369, 111,       1) /* SizeMod */;

INSERT INTO `weenie_properties_string` (`object_Id`, `type`, `value`)
VALUES (450369,   1, 'Sanguinary Aegis') /* Name */
     , (450369,  16, 'A crystalline barrier infused with the magical properties of distilled chorizite.  Although the Aegis provides no physical protection, the aura generated by the shield will negate a portion of all magical projectile attacks, based upon the wielder''s abilities.') /* LongDesc */;

INSERT INTO `weenie_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (450369,   1, 0x02000578) /* Setup */
     , (450369,   3, 0x20000014) /* SoundTable */
     , (450369,   6, 0x04000BEF) /* PaletteBase */
     , (450369,   7, 0x10000157) /* ClothingBase */
     , (450369,   8, 0x060012F7) /* Icon */
     , (450369,  22, 0x3400002B) /* PhysicsEffectTable */;
