DELETE FROM `weenie` WHERE `class_Id` = 450371;

INSERT INTO `weenie` (`class_Id`, `class_Name`, `type`, `last_Modified`)
VALUES (450371, 'shieldsanguinaryredtailor', 1, '2021-11-17 16:56:08') /* Generic */;

INSERT INTO `weenie_properties_int` (`object_Id`, `type`, `value`)
VALUES (450371,   1,          2) /* ItemType - Armor */
     , (450371,   3,         14) /* PaletteTemplate - Red */
     , (450371,   5,        0) /* EncumbranceVal */
     , (450371,   8,        140) /* Mass */
     , (450371,   9,    2097152) /* ValidLocations - Shield */
     , (450371,  16,          1) /* ItemUseable - No */
     , (450371,  19,          20) /* Value */
     , (450371,  27,          2) /* ArmorType - Leather */
     , (450371,  28,          0) /* ArmorLevel */
     , (450371,  51,          4) /* CombatUse - Shield */
     , (450371,  93,       1044) /* PhysicsState - Ethereal, IgnoreCollisions, Gravity */
     , (450371, 150,        103) /* HookPlacement - Hook */
     , (450371, 151,          2) /* HookType - Wall */;

INSERT INTO `weenie_properties_bool` (`object_Id`, `type`, `value`)
VALUES (450371,  22, True ) /* Inscribable */
     , (450371,  69, False) /* IsSellable */;

INSERT INTO `weenie_properties_float` (`object_Id`, `type`, `value`)
VALUES (450371,  13,       0) /* ArmorModVsSlash */
     , (450371,  14,       0) /* ArmorModVsPierce */
     , (450371,  15,       0) /* ArmorModVsBludgeon */
     , (450371,  16,       0) /* ArmorModVsCold */
     , (450371,  17,       0) /* ArmorModVsFire */
     , (450371,  18,       0) /* ArmorModVsAcid */
     , (450371,  19,       0) /* ArmorModVsElectric */
     , (450371,  39,       1) /* DefaultScale */
     , (450371, 110,       1) /* BulkMod */
     , (450371, 111,       1) /* SizeMod */;

INSERT INTO `weenie_properties_string` (`object_Id`, `type`, `value`)
VALUES (450371,   1, 'Sanguinary Aegis') /* Name */
     , (450371,  16, 'A crystalline barrier infused with the magical properties of distilled chorizite.  Although the Aegis provides no physical protection, the aura generated by the shield will negate a portion of all magical projectile attacks, based upon the wielder''s abilities.') /* LongDesc */;

INSERT INTO `weenie_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (450371,   1, 0x0200057B) /* Setup */
     , (450371,   3, 0x20000014) /* SoundTable */
     , (450371,   6, 0x04000BEF) /* PaletteBase */
     , (450371,   7, 0x1000015A) /* ClothingBase */
     , (450371,   8, 0x060012F7) /* Icon */
     , (450371,  22, 0x3400002B) /* PhysicsEffectTable */;
