DELETE FROM `weenie` WHERE `class_Id` = 450374;

INSERT INTO `weenie` (`class_Id`, `class_Name`, `type`, `last_Modified`)
VALUES (450374, 'ace450374-ravenaegistailor', 1, '2021-11-17 16:56:08') /* Generic */;

INSERT INTO `weenie_properties_int` (`object_Id`, `type`, `value`)
VALUES (450374,   1,          2) /* ItemType - Armor */
     , (450374,   3,          9) /* PaletteTemplate - Grey */
     , (450374,   5,        0) /* EncumbranceVal */
     , (450374,   9,    2097152) /* ValidLocations - Shield */
     , (450374,  16,          1) /* ItemUseable - No */
     , (450374,  18,         32) /* UiEffects - Fire */
     , (450374,  19,          20) /* Value */
     , (450374,  28,          0) /* ArmorLevel */
     , (450374,  51,          4) /* CombatUse - Shield */
     , (450374,  93,       1044) /* PhysicsState - Ethereal, IgnoreCollisions, Gravity */
     , (450374, 151,          2) /* HookType - Wall */;

INSERT INTO `weenie_properties_bool` (`object_Id`, `type`, `value`)
VALUES (450374,  22, True ) /* Inscribable */
     , (450374,  69, False) /* IsSellable */
     , (450374,  99, True ) /* Ivoryable */;

INSERT INTO `weenie_properties_float` (`object_Id`, `type`, `value`)
VALUES (450374,   5,  -0.025) /* ManaRate */
     , (450374,  13,       0) /* ArmorModVsSlash */
     , (450374,  14,       0) /* ArmorModVsPierce */
     , (450374,  15,       0) /* ArmorModVsBludgeon */
     , (450374,  16,       0) /* ArmorModVsCold */
     , (450374,  17,       0) /* ArmorModVsFire */
     , (450374,  18,       0) /* ArmorModVsAcid */
     , (450374,  19,       0) /* ArmorModVsElectric */;

INSERT INTO `weenie_properties_string` (`object_Id`, `type`, `value`)
VALUES (450374,   1, 'Raven Aegis') /* Name */
     , (450374,  16, 'A magically imbued Aegis crafted by the Order of the Raven Hand.  Although the Aegis provides no physical protection, the aura generated by the shield will negate a portion of all magical projectile attacks, based upon the wielder''s abilities.') /* LongDesc */;

INSERT INTO `weenie_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (450374,   1, 0x02001441) /* Setup */
     , (450374,   3, 0x20000014) /* SoundTable */
     , (450374,   7, 0x10000817) /* ClothingBase */
     , (450374,   8, 0x06006056) /* Icon */
     , (450374,  22, 0x3400002B) /* PhysicsEffectTable */
     , (450374,  37,          6) /* ItemSkillLimit - MeleeDefense */;

