namespace ACE.Network.Enum 
{
    public enum Useability : uint
    {
        USEABLE_UNDEF                                           = 0,
        USEABLE_NO                                              = 1,
        USEABLE_SELF                                            = 2,
        USEABLE_WIELDED                                         = 4,
        USEABLE_CONTAINED                                       = 8,
        USEABLE_VIEWED                                          = 16,
        USEABLE_CONTAINED_VIEWED                                = 24,
        USEABLE_REMOTE                                          = 32,
        USEABLE_NEVER_WALK                                      = 64,
        USEABLE_CONTAINED_VIEWED_REMOTE                         = 56,
        USEABLE_VIEWED_REMOTE                                   = 48,
        USEABLE_VIEWED_REMOTE_NEVER_WALK                        = 112,
        USEABLE_REMOTE_NEVER_WALK                               = 96,
        USEABLE_CONTAINED_VIEWED_REMOTE_NEVER_WALK              = 120,
        USEABLE_OBJSELF                                         = 128,
        USEABLE_SOURCE_WIELDED_TARGET_WIELDED                   = 262148,
        USEABLE_SOURCE_WIELDED_TARGET_CONTAINED                 = 524292,
        USEABLE_SOURCE_WIELDED_TARGET_VIEWED                    = 1048580,
        USEABLE_SOURCE_WIELDED_TARGET_REMOTE                    = 2097156,
        USEABLE_SOURCE_WIELDED_TARGET_REMOTE_NEVER_WALK         = 6291460,
        USEABLE_SOURCE_CONTAINED_TARGET_WIELDED                 = 262152,
        USEABLE_SOURCE_CONTAINED_TARGET_CONTAINED               = 524296,
        USEABLE_SOURCE_CONTAINED_TARGET_OBJSELF_OR_CONTAINED    = 8912904,
        USEABLE_SOURCE_CONTAINED_TARGET_SELF_OR_CONTAINED       = 655368,
        USEABLE_SOURCE_CONTAINED_TARGET_VIEWED                  = 1048584,
        USEABLE_SOURCE_CONTAINED_TARGET_REMOTE                  = 2097160,
        USEABLE_SOURCE_CONTAINED_TARGET_REMOTE_NEVER_WALK       = 6291464,
        USEABLE_SOURCE_CONTAINED_TARGET_REMOTE_OR_SELF          = 2228232,
        USEABLE_SOURCE_VIEWED_TARGET_WIELDED                    = 262160,
        USEABLE_SOURCE_VIEWED_TARGET_CONTAINED                  = 524304,
        USEABLE_SOURCE_VIEWED_TARGET_VIEWED                     = 1048592,
        USEABLE_SOURCE_VIEWED_TARGET_REMOTE                     = 2097168,
        USEABLE_SOURCE_REMOTE_TARGET_WIELDED                    = 262176,
        USEABLE_SOURCE_REMOTE_TARGET_CONTAINED                  = 524320,
        USEABLE_SOURCE_REMOTE_TARGET_VIEWED                     = 1048608,
        USEABLE_SOURCE_REMOTE_TARGET_REMOTE                     = 2097184,
        USEABLE_SOURCE_REMOTE_TARGET_REMOTE_NEVER_WALK          = 6291488,
        USEABLE_SOURCE_MASK = 65535,
        // USEABLE_TARGET_MASK = -65536,
    }
}