namespace ACE.Server.Network.Sequence
{
    public enum SequenceType
    {
        ObjectPosition                        = 0,
        ObjectMovement                        = 1,
        ObjectState                           = 2,
        ObjectVector                          = 3,
        ObjectTeleport                        = 4,
        ObjectServerControl                   = 5,
        ObjectForcePosition                   = 6,
        ObjectVisualDesc                      = 7,
        ObjectInstance                        = 8,

        Motion,

        PrivateUpdateAttribute,
        PrivateUpdateAttribute2ndLevel,
        PrivateUpdateSkill,

        PrivateUpdatePropertyInt,
        PrivateUpdatePropertyInt64,        
        PrivateUpdatePropertyBool,
        PrivateUpdatePropertyDouble,        
        PrivateUpdatePropertyDataID,
        PrivateUpdatePropertyInstanceID,
        PrivateUpdatePropertyString,

        PrivateUpdateAttribute2ndLevelHealth,
        PrivateUpdateAttribute2ndLevelStamina,
        PrivateUpdateAttribute2ndLevelMana,

        PublicUpdatePropertyInt,
        PublicUpdatePropertyInt64,
        PublicUpdatePropertyBool,
        PublicUpdatePropertyDouble,
        PublicUpdatePropertyDataID,
        PublicUpdatePropertyInstanceId,
        PublicUpdatePropertyString,

        SetStackSize,
        Confirmation,

        PrivateUpdateAttributeStrength,
        PrivateUpdateAttributeEndurance,
        PrivateUpdateAttributeQuickness,
        PrivateUpdateAttributeCoordination,
        PrivateUpdateAttributeFocus,
        PrivateUpdateAttributeSelf,

        PrivateUpdateSkillAxe,
        PrivateUpdateSkillBow,
        PrivateUpdateSkillCrossBow,
        PrivateUpdateSkillDagger,
        PrivateUpdateSkillMace,
        PrivateUpdateSkillMeleeDefense,
        PrivateUpdateSkillMissileDefense,
        PrivateUpdateSkillSling,
        PrivateUpdateSkillSpear,
        PrivateUpdateSkillStaff,
        PrivateUpdateSkillSword,
        PrivateUpdateSkillThrownWeapon,
        PrivateUpdateSkillUnarmedCombat,
        PrivateUpdateSkillArcaneLore,
        PrivateUpdateSkillMagicDefense,
        PrivateUpdateSkillManaConversion,
        PrivateUpdateSkillSpellcraft,
        PrivateUpdateSkillItemAppraisal,
        PrivateUpdateSkillPersonalAppraisal,
        PrivateUpdateSkillDeception,
        PrivateUpdateSkillHealing,
        PrivateUpdateSkillJump,
        PrivateUpdateSkillLockpick,
        PrivateUpdateSkillRun,
        PrivateUpdateSkillAwareness,
        PrivateUpdateSkillArmsAndArmorRepair,
        PrivateUpdateSkillCreatureAppraisal,
        PrivateUpdateSkillWeaponAppraisal,
        PrivateUpdateSkillArmorAppraisal,
        PrivateUpdateSkillMagicItemAppraisal,
        PrivateUpdateSkillCreatureEnchantment,
        PrivateUpdateSkillItemEnchantment,
        PrivateUpdateSkillLifeMagic,
        PrivateUpdateSkillWarMagic,
        PrivateUpdateSkillLeadership,
        PrivateUpdateSkillLoyalty,
        PrivateUpdateSkillFletching,
        PrivateUpdateSkillAlchemy,
        PrivateUpdateSkillCooking,
        PrivateUpdateSkillSalvaging,
        PrivateUpdateSkillTwoHandedCombat,
        PrivateUpdateSkillGearcraft,
        PrivateUpdateSkillVoidMagic,
        PrivateUpdateSkillHeavyWeapons,
        PrivateUpdateSkillLightWeapons,
        PrivateUpdateSkillFinesseWeapons,
        PrivateUpdateSkillMissileWeapons,
        PrivateUpdateSkillShield,
        PrivateUpdateSkillDualWield,
        PrivateUpdateSkillRecklessness,
        PrivateUpdateSkillSneakAttack,
        PrivateUpdateSkillDirtyFighting,
        PrivateUpdateSkillChallenge,
        PrivateUpdateSkillSummoning
    }
}
